
//macros
#define GRID_W (pixelW * pixelGrid)
#define GRID_H (pixelH * pixelGrid)
#define NOKIA_H (safezoneH)
#define NOKIA_W (((safezoneH / GRID_H) / 2) * GRID_W)
#define SCREEN_W (0.584 * NOKIA_W)
#define SCREEN_H (0.13302 * NOKIA_H)

//idcs
#define IDC_HISTORY 7
#define IDC_ENTERTEXT 8

#define IDC_CTRLGROUP_HOME 10
#define IDC_HOME_CARRIER 101
#define IDC_HOME_BACKGROUND 102
#define IDC_HOME_BATTERY 103
#define IDC_HOME_CLOCK 104

#define IDC_CTRLGROUP_MAINMENU 11
#define IDC_MAINMENU_TEXT 111
#define IDC_MAINMENU_PICTURE 112

#define IDC_CTRLGROUP_TONES 12
#define IDC_TONES_SETTING 121
#define IDC_TONES_VALUE 122
#define IDC_TONES_LIST 123

#define IDC_CTRLGROUP_PHONEBOOK 13
#define IDC_PHONEBOOK_CONTACTS 131
#define IDC_PHONEBOOK_SETTINGS 132
#define IDC_PHONEBOOK_VIEW_NAME 133
#define IDC_PHONEBOOK_VIEW_NUMBER 134

#define IDC_CTRLGROUP_ALARM 14
#define IDC_ALARM_SET_PICTURE 141
#define IDC_ALARM_SET_TEXT 142
#define IDC_ALARM_SET_EDIT 143
